"""add_agent_definition

Revision ID: 3fc028576a36
Revises: 02e36f737c9f
Create Date: 2026-05-26 00:09:13.609941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc028576a36'
down_revision: Union[str, None] = '02e36f737c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('model_provider', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('reasoning_strategy', sa.String(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_definitions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_definitions_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_definitions_type'))
        batch_op.drop_index(batch_op.f('ix_agent_definitions_org_id'))

    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
