"""add_agent_tool_configs

Revision ID: c65b814769a4
Revises: 5688c429ddf0
Create Date: 2026-05-26 01:49:29.206753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c65b814769a4'
down_revision: Union[str, None] = '5688c429ddf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tool_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'name', name='uq_agent_tool_config_agent_name')
    )
    with op.batch_alter_table('agent_tool_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tool_configs_agent_id'), ['agent_id'], unique=False)

    op.drop_table('_alembic_tmp_agent_definitions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_agent_definitions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('definition', sqlite.JSON(), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'org_id', name='uq_agent_def_name_org')
    )
    with op.batch_alter_table('agent_tool_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tool_configs_agent_id'))

    op.drop_table('agent_tool_configs')
    # ### end Alembic commands ###
